import { prisma } from '../db/prisma.js';
import { logger } from '../utils/logger.js';

export async function generateMonthlyReport(userId: string, month: string) {
  try {
    logger.info(`Generating monthly report for user ${userId}, month ${month}`);

    // Parse month (format: YYYY-MM)
    const startDate = new Date(`${month}-01`);
    const endDate = new Date(startDate);
    endDate.setMonth(endDate.getMonth() + 1);

    // Get transactions
    const transactions = await prisma.transaction.findMany({
      where: {
        userId,
        date: {
          gte: startDate,
          lt: endDate,
        },
      },
    });

    // Calculate totals
    const totals = {
      income: transactions
        .filter((t) => t.direction === 'income')
        .reduce((sum, t) => sum + t.amount, 0),
      expense: transactions
        .filter((t) => t.direction === 'expense')
        .reduce((sum, t) => sum + t.amount, 0),
      net: 0,
      byCategory: {} as Record<string, number>,
    };

    totals.net = totals.income - totals.expense;

    transactions.forEach((tx) => {
      if (tx.direction === 'expense' && tx.category) {
        totals.byCategory[tx.category] = (totals.byCategory[tx.category] || 0) + tx.amount;
      }
    });

    // Get insights for the period
    const insights = await prisma.insight.findMany({
      where: {
        userId,
        period: month,
      },
    });

    // Get tax notes
    const taxNotes = await prisma.taxNote.findMany({
      where: {
        userId,
      },
    });

    // Generate highlights
    const highlights: string[] = [];
    
    if (totals.net > 0) {
      highlights.push(`Positive cash flow of ₹${totals.net.toFixed(2)} this month`);
    } else {
      highlights.push(`Negative cash flow of ₹${Math.abs(totals.net).toFixed(2)} this month`);
    }

    const topCategory = Object.entries(totals.byCategory).sort((a, b) => b[1] - a[1])[0];
    if (topCategory) {
      highlights.push(`Top spending category: ${topCategory[0]} (₹${topCategory[1].toFixed(2)})`);
    }

    if (insights.length > 0) {
      highlights.push(`${insights.length} financial insights available`);
    }

    if (taxNotes.length > 0) {
      highlights.push(`${taxNotes.length} tax deduction opportunities identified`);
    }

    // Generate chart data references (would be generated by frontend)
    const charts = [
      'income-vs-expense',
      'category-breakdown',
      'spending-trend',
      'top-merchants',
    ];

      // Create or update report
      const existingReport = await prisma.report.findUnique({
        where: {
          userId_month: {
            userId,
            month,
          },
        },
      });

      const report = existingReport
        ? await prisma.report.update({
            where: { id: existingReport.id },
            data: {
              totals,
              highlights,
              charts,
              insightIds: insights.map((i) => i.id),
              taxNoteIds: taxNotes.map((t) => t.id),
              generatedAt: new Date(),
            },
          })
        : await prisma.report.create({
            data: {
              userId,
              month,
              totals,
              highlights,
              charts,
              insightIds: insights.map((i) => i.id),
              taxNoteIds: taxNotes.map((t) => t.id),
            },
          });

    logger.info(`Monthly report generated for user ${userId}, month ${month}`);
    return report;
  } catch (error) {
    logger.error('Error generating monthly report:', error);
    throw error;
  }
}

